name       : sd
version    : 0.7.6
release    : 1
source     :
    - https://github.com/chmln/sd/archive/refs/tags/v0.7.6.tar.gz : faf33a97797b95097c08ebb7c2451ac9835907254d89863b10ab5e0813b5fe5f
license    : MIT
component  : system.utils
summary    : Intuitive find & replace CLI (sed alternative)
description: |
    sd is an intuitive find & replace CLI.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/sd $installdir/usr/bin/sd
    install -Dm00644 target/release/build/sd-*/out/_sd $installdir/usr/share/zsh/site-functions/_sd
    install -Dm00644 target/release/build/sd-*/out/sd.bash $installdir/usr/share/bash-completion/completions/sd
    install -Dm00644 target/release/build/sd-*/out/sd.fish $installdir/usr/share/fish/vendor_completions.d/sd.fish
    install -Dm00644 target/release/build/sd-*/out/sd.1 $installdir/usr/share/man/man1/sd.1
check      : |
    cargo test --all
